#! /bin/bash
## For making batches of diagrams.
## Usage: croplatex filename1 filename2 ...
## Creates a folder 'diagrams' if it doesn't exist.
## Runs LaTeX*2->dvips->ps2pdf then crops the resulting files and moves them to the diagrams folder.
## Then opens them for verification -- easy to remove this line if you don't want to see them all.
## Also tidies up after itself.
## Works whether you give it a TeX file with or without the extension.

# if [ ! -d ./diagrams ]
# then
#   mkdir diagrams
# fi

for filename in "$@"
do
  if [[ $filename == *.tex ]]
  then
    basename=${filename/.tex/}
  else
    basename=$filename
  fi
  echo $basename
  latex "$basename"
  latex "$basename"
  dvips "$basename"
  ps2pdf "$basename.ps"

  pdfcrop --margins 2 "$basename.pdf"
  # mv "$basename-crop.pdf" "diagrams/$basename.pdf"
  mv "$basename-crop.pdf" "$basename.pdf"
  # open "diagrams/$basename.pdf"
  open "$basename.pdf"

  rm $basename.dvi $basename.ps $basename.pdf
done

latexmk -c

## Some of my tree-drawing packages create a pst-tree.aux file.
## This removes it if it exists.
if [ -f "pst-tree.aux" ]
then
  rm "pst-tree.aux"
fi
