#! /bin/bash
## Runs LaTeX->BibTeX->LaTeX*2->dvips->ps2pdf then opens the resulting PDF and tidies up with latexmk (https://www.ctan.org/pkg/latexmk/?lang=en).
## Works whether you give it a TeX file with or without the extension.

if [[ "$1" == *.tex ]]
then
  basename=${1/.tex/}
else
  basename=$1
fi

latex "$basename"
bibtex "$basename"
latex "$basename"
latex "$basename"
dvips "$basename"
ps2pdf "$basename.ps"

open "$basename.pdf"

latexmk -c
rm $basename.dvi $basename.ps

## Some of my tree-drawing packages create a pst-tree.aux file.
## This removes it if it exists.
if [ -f "pst-tree.aux" ]
then
  rm "pst-tree.aux"
fi
