#! /bin/bash
## Usage: mkdiagram n
## Creates n blank LaTeX files to add diagrams to for cropping with croplatex.
## To just make one file, you can leave out the argument.

# Initialise count
count=1

if [[ "$1" == 0 ]]
then
  echo "Error: can't make 0 files. Use a positive number."
else
  while [[ "$count" -le "${1:-1}" ]]
  do
## Replace this string with whatever you want in your bare diagram file.
    echo "\documentclass{article}
\usepackage{mary-trees}
\begin{document}
\thispagestyle{empty}
% Write here

\end{document}" > "diagram-$count.tex"
    count=$((count+1))
  done
fi
