#! /bin/bash
## Usage: mkdiagram n
## Creates n blank LaTeX files to add diagrams to for cropping with croplatex.
## To just make one file, you can leave out the argument.

# Initialise variables
count=1
filenumber=1

if [[ "$1" == 0 ]]
then
  echo "Error: can't make 0 files. Use a positive number."
else
  while [[ "$count" -le "${1:-1}" ]] # Use the 1st argument, or '1' if no argument is provided.
  do
    if [[ -f "diagram-$filenumber.tex" ]]
    then
      filenumber=$((filenumber+1))  # Increases the filenumber variable for each file that already exists
    else
## Replace this string with whatever you want in your bare diagram file.
    echo "\documentclass{article}
\usepackage{mary-trees}
\begin{document}
\thispagestyle{empty}
% Write here

\end{document}" > "diagram-$filenumber.tex"
    count=$((count+1))
  fi
  done
fi
