#! /bin/bash
## Usage: newslides (filename)
## Creates and opens a ready-to-use LaTeX file with my default diagram template.
## Replace the value of $text with your desired content.
## If no filename is given, produces 'new-diagram.tex'

text="
\documentclass[a4paper,noamsthm,handout]{beamer} %add handout and gray as option for handout and un-percent \usepackage{pgfpages} and \pgfpagesuselayout{2 on 1}[a4paper,border shrink=5mm] below!



\mode<presentation>
{
   \usetheme[secheader]{Boadilla}

  %FOR HANDOUT:
 %\usetheme{default}

  %\setbeamercovered{transparent}
  % or whatever (possibly just delete it)
}
%\usepackage{pgfpages}
%\pgfpagesuselayout{4 on 1}[a4paper,landscape,border shrink=20mm]
%\usepackage{times}

\usepackage[greek, ngerman, english]{babel}
\usepackage{xcolor}
\usepackage[OT2,OT1]{fontenc}
\usepackage[T1]{fontenc}
\usepackage[10pt]{type1ec}
\usepackage{lmodern}
\usepackage{amssymb}
\usepackage{amsfonts}
\usepackage{teubner}
\usepackage{tipa}
\usepackage{avm}
\usepackage{pifont}
\usepackage{textcomp}
%\usepackage{xyling}
\usepackage{tikz}
\usepackage{tikz-qtree}
\usetikzlibrary{babel,tikzmark}
\usepackage{pstricks}
\usepackage{pst-node}
%\usepackage{verse}
\usepackage{fixltx2e}
\usepackage{covington}
\usepackage{soul}
%\usepackage{tree-dvips}
\usepackage{stmaryrd}
%\usepackage{devanagari}
%\usepackage[utf8x]{inputenc}
\usepackage{natbib}
%\usepackage{index}
\usepackage{gb4e}
\newcommand\jjnt[1]{} %{\marginpar{#1}} % OR {}
\newcommand\ie[1]{\textipa{\emph{#1}}}
\newcommand{\ieind}[2]{\textipa{\emph{#1}}}
\newcommand\greek[1]{\textgreek{#1}}
\newcommand\g{\textg}
\newcommand\iecap[1]{\slshape{\*{#1}}}
\newcommand\subscript[1]{\textsubscript{#1}}
\newcommand\larynum[1]{\textsubscript{\slshape{\*{#1}}}}
\newcommand\Rgveda{\textipa{\emph{\d {\*R}\textg veda}}}
\newcommand{\textcyrillic}[1]{#1}
%\newcommand\approot[2]{\section*{\Large \textipa{\emph{$\surd$#1}} `#2'}}
%\newcommand\vbrt[2][]{\super{#1}$\surd$\textipa{\emph{#2}}}
%\newcommand{\vsind}[2]{#1\index[loc]{#2!#1}}
%\newcommand{\vsinb}[2]{#1\index[loc]{#2!\textbf{#1}}}
\newcommand\german[1]{\foreignlanguage{ngerman}{#1}}
\newcommand\french[1]{\foreignlanguage{frenchb}{#1}}
\newcommand\rvl[3]{#1}%OR: \rvl[3]{#1} OR \rvl[3]{\emph{#2}
\newcommand\subs[1]{\textsubscript{#1}}
\newcommand\mnwd[1]{\ul{#1}}
\newcommand\mntl[1]{\emph{#1}}
%\newcommand\vnho{\super{\tiny{o}}}
%\newcommand\rc[5][12]{\begin{example}\label{#2}
%\settowidth{\versewidth}{yah sambaram parvatesu ksiyantam and a lot lot more,}
%\begin{verse}[\versewidth]
%\indentpattern{#1}
%\begin{patverse*}
%\textipa{\emph{#4}}\hspace{\stretch{1}} (#3 #2)
%\end{patverse*}
%
%\begin{patverse*}
%`#5'
%\end{patverse*}
%\end{verse}
%\end{example}}
%\renewcommand{\Treelfg}[2][0]{\Treek[#1]{3}{#2}}
%\renewcommand{\Klfg}[5][0]{%
%\K[#1]{#2}\Below{{\textsc{#3$\uparrow$#4$\downarrow$#5}}}}
%\newcommand{\Klfgx}[5][0]{%
%\K[#1]{#2}\Below{{\textsc{#3$\downarrow$#4$\uparrow$#5}}}}
%\newcommand{\Klfgy}[3][0]{%
%\K[#1]{#2}\Below{#3}}
%\renewcommand{\Blfg}[1]{\Bk{-5}{0}{#1}}
%\newcommand{\Blfgkk}[5]{\Bkk{#1,#2-5}{#3,#4}{#5}}
%\renewcommand{\eachwordone}{\slshape}
%\setlength{\parindent}{0cm}
\setlength{\parskip}{1ex plus 0.2 ex minus 0.2ex}
%\setlength{\oddsidemargin}{0.25cm}
%\setlength{\textwidth}{15cm}
%\addtolength{\hoffset}{-2cm}
%\addtolength{\textwidth}{4cm}
%\addtolength{\voffset}{-2cm}
%\addtolength{\textheight}{3cm}
%\defcitealias{RenouEVP}{EVP}
%\defcitealias{Mayrhofer86}{EWA}
%\defcitealias{WackernagelDebrunnerAiG}{AiG}
%\defcitealias{Oldenberg09}{Noten}
%\defcitealias{Geldner51f}{RV}
%\defcitealias{Krisch06}{RIVELEX}
%\setlength{\oddsidemargin}{0.25cm}
%\setlength{\textwidth}{15cm}
%\addtolength{\hoffset}{-2cm}
%\addtolength{\textwidth}{4cm}
%\addtolength{\voffset}{-2cm}
%\addtolength{\textheight}{3cm}
\renewcommand\newblock{\hskip .11em plus .33em minus .07em}
\newcommand{\rsection}[1]{\section{\rmfamily #1}}
\newcommand{\rsubsection}[1]{\subsection{\rmfamily #1}}
\newcommand{\rframetitle}[1]{\frametitle{\rmfamily #1}}
\newcommand{\lang}[2][35pt]{\hspace{#1}\textcolor{magenta}{#2}\vspace{-10pt}}

\newcommand{\gap}{\rule{0.6cm}{0.01cm}}
\beamertemplatenavigationsymbolsempty

\title[Short title]{Long title}

 \resetcounteronoverlays{exx}

\author{\rmfamily Jamie Findlay}
\institute[]{\rmfamily Faculty of Linguistics, Philology, and Phonetics}
\date{\rmfamily Week 2, TT 2018}
\titlegraphic{\includegraphics[width=2cm]{oxcol}}


\begin{document}


\begin{frame}
  \thispagestyle{empty}
\titlepage
\end{frame}




\begin{frame}


\end{frame}



\end{document}
"

filenumber=1

## Cleans input so user can include the .tex the extension or not.
if [[ "$1" == *.tex ]]
then
  filename=${1/.tex/}
else
  filename=${1:-"new"}
fi

## Counts how many untitled ('new') files already exist past the first.
while [[ -f "new($filenumber).tex" ]]; do
  filenumber=$((filenumber+1))
done

## If making a blank file, calls it 'new'; if there's already a file called 'new', adds bracketed numbers after to differentiate (so you won't overwrite your blank file if you make another one).
if [[ "$filename" == "new" ]]; then
  if [[ -f "new.tex" ]]; then
    echo "$text" > "$filename($filenumber).tex"
		open "$filename($filenumber).tex"
  else
    echo "$text" > "$filename.tex"
		open "$filename.tex"
  fi
## Checks if your filename is in use -- returns error if so, otherwise makes it.
else
  if [[ -f "$filename.tex" ]]
  then
    echo "Error: file already exists!"
  else
    echo "$text" > "$filename.tex"
		open "$filename.tex"
  fi
fi
