#! /bin/bash
## Removes everything that LaTeX produces and leaves just the TeX file behind.
## Good for testing things.

rm *.pdf *.ps *.dvi *.bbl *.aux *.idx *.ind *.lof *.lot *.out *.toc *.acn *.acr *.alg *.glg *.glo *.gls *.ist *.bcf *.fdb_latexmk *.fls *.log *.run.xml *.synctex.gz *.blg 2> /dev/null
